In [26]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import Imputer
from io import StringIO

In [13]:
csv_data = '''A, B, C, D
                    1.0, 2.0, 3.0, 4.0
                    5.0, 6.0,, 8.0
                    10.0, 11.0, 12.0  '''

df = pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [14]:
df.isnull().sum()

A     0
 B    0
 C    1
 D    1
dtype: int64

In [16]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

In [24]:
imr = Imputer(missing_values='NaN', strategy='mean', axis=1)
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

/anaconda3/envs/test1/lib/python3.7/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  6.33333333,  8.        ],
       [10.        , 11.        , 12.        , 11.        ]])

In [29]:
np.unique(df.values[:,0:2])

array([ 1.,  2.,  5.,  6., 10., 11.])

In [33]:
df['A'].values

array([ 1.,  5., 10.])